import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'City Car calculadora',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <link rel="icon" href="/citycar-logo.jpg" />
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
